### ISSUE TITLE
评论系统

### ISSUE THREAD

**Issue by Ezgx** [hdxw/hexo-theme-prowiki#2]
没有评论系统支持吗

**Comment by hdxw** [comment]
评论属于插件(Plugins)，本项目属于(Themes)，只负责页面渲染。

如需评论功能可以尝试添加插件[hexo-plugin-gitalk](https://github.com/snowdreams1006/hexo-plugin-gitalk)，相关说明[参考这里](https://demo.wujiaxing.com/prowiki/about/#hexo-plugin-gitalk-评论)

关于更新，本主题创建目的是个人博客使用，更新内容看我遇到使用需求，不会经常更新。

如果想在本项目基础上创建分支可以fork后编辑，部署时替换到hexo项目的themes文件夹。
